version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  main:
    jobs:
      - build-package




jobs:
  build-package:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          pip-dependency-file: requirements.txt
      - python/install-packages:
          pkg-manager: pip
          args: build
      - run:
          name: build
          command: python -m build
      - run: # FIXME
          name: rename
          command: mv dist/crypto_package-0.0.1-py3-none-any.whl dist/crypto_package_fake_bot-0.0.1-py3-none-any.whl
      - run:
          name: delete fake_bot #FIXME
          command: rm -r crypto_package/backtesting
      - run:
          name: build #FIXME
          command: python -m build
      - store_artifacts:
          path: dist/
