from crypto_package.candles.topic_subscribtion import subscribe_on_topics
from crypto_package.candles.topic_subscribtion import unsubscribe_on_topics
from crypto_package.candles.get_candles import get_candles
from crypto_package.candles.live_prices import get_live_price
# from crypto_package.fake_bot.fake_bot import FakeBot
# from crypto_package.fake_bot.analyze_functions import plot_balance